### ISSUE TITLE
tag filtering in all sections

### ISSUE THREAD

**Issue by BTunca** [paulmartins/hugo-digital-garden-theme#2]
Hi!

Love your theme! I noticed that under the "garden" main page (https://hugo-digital-garden-demo.netlify.app/garden/) There is an option to filter the content based on the tags. This filter is not available under the "projects" or "library".

Is it possible to turn on this tag filter for all sections?

Again, thank you for your effort with this wonderful theme.

Best,
BTunca

**Comment by paulmartins** [comment]
Hi @BTunca,

Thanks for taking a look at the theme.
The filter is powered by this JS add-on: https://isotope.metafizzy.co/
I'm afraid I don't have a lot of time at the moment to integrate it to other pages but will be happy to review a pull request if you want to give it a go. Otherwise I'll come back to it later on.

Yours,
Paul

**Comment by BTunca** [comment]
Thank you for your reply! Since I do not have the competence to do that, I will be looking forward to seeing it in the future as I continue working on my website.

Again, great theme!

/BTunca

**Comment by paulmartins** [comment]
@BTunca, this should now be available in the master branch thanks to @nanqunchen so I'll close this for now :)

**Comment by BTunca** [comment]
@paulmartins sorry for my late response, thank you! Much appreciated!
